# Generated by Django 4.1 on 2023-02-11 23:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('featured', models.BooleanField()),
                ('event_date', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bible_verse', models.CharField(choices=[('genesis', 'Genesis'), ('exodus', 'Exodus'), ('leviticus', 'Leviticus'), ('numbers', 'Numbers'), ('deuteronomy', 'Deuteronomy'), ('joshua', 'Joshua'), ('judges', 'Judges'), ('ruth', 'Ruth'), ('1 samuel', '1 Samuel'), ('2 samuel', '2 Samuel'), ('1 kings', '1 Kings'), ('2 kings', '2 Kings'), ('1 chronicles', '1 Chronicles'), ('2 chronicles', '2 Chronicles'), ('ezra', 'Ezra'), ('nehemiah', 'Nehemiah'), ('esther', 'Esther'), ('job', 'Job'), ('psalm', 'Psalm'), ('proverbs', 'Proverbs'), ('ecclesiastes', 'Ecclesiastes'), ('song of solomon', 'Song of Solomon'), ('isaiah', 'Isaiah'), ('jeremiah', 'Jeremiah'), ('lamentations', 'Lamentations'), ('ezekiel', 'Ezekiel'), ('daniel', 'Daniel'), ('hosea', 'Hosea'), ('joel', 'Joel'), ('amos', 'Amos'), ('obadiah', 'Obadiah'), ('jonah', 'Jonah'), ('micah', 'Micah'), ('nahum', 'Nahum'), ('habakkuk', 'Habakkuk'), ('zephaniah', 'Zephaniah'), ('haggai', 'Haggai'), ('zechariah', 'Zechariah'), ('malachi', 'Malachi'), ('matthew', 'Matthew'), ('mark', 'Mark'), ('luke', 'Luke'), ('john', 'John'), ('acts', 'Acts'), ('romans', 'Romans'), ('1 corinthians', '1 Corinthians'), ('2 corinthians', '2 Corinthians'), ('galatians', 'Galatians'), ('ephesians', 'Ephesians'), ('philippians', 'Philippians'), ('colossians', 'Colossians'), ('1 thessalonians', '1 Thessalonians'), ('2 thessalonians', '2 Thessalonians'), ('1 timothy', '1 Timothy'), ('2 timothy', '2 Timothy'), ('titus', 'Titus'), ('philemon', 'Philemon'), ('hebrews', 'Hebrews'), ('james', 'James'), ('1 peter', '1 Peter'), ('2 peter', '2 Peter'), ('1 john', '1 John'), ('2 john', '2 John'), ('3 john', '3 John'), ('jude', 'Jude'), ('revelation', 'Revelation')], max_length=20)),
                ('ref', models.CharField(help_text='Write in this format:                             chapter:verse and chapter:start-end in case of range', max_length=10)),
                ('date_for', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('post_image', models.ImageField(upload_to='media/')),
                ('body', ckeditor.fields.RichTextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
